{% set name = "evargs" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evargs-{{ version }}.tar.gz
  sha256: 1993d3e6563f82ce2097e6455b043c6b327acb4b2342ab82ee94a6644f63b6cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - python >={{ python_min }}

test:
  imports:
    - evargs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/deer-hunt/evargs
  license: MIT
  license_file: LICENSE.md
  summary: '"EvArgs" is a lightweight python module for easy expression parsing and value-casting, validating by rules, and it provides flexible configuration and custom validation method.'
  description: |
    [Features]:
    - It can specify the condition or value-assignment using a simple expression. e.g. "a=1;b=5"
    - Evaluate assigned values. e.g "evargs.evaluate('a', 1)"
    - Put values. It's available to using "put" is without parsing the expression.
    - Value casting - str, int, float, complex...
    - Value validation - unsigned, number range, alphabet, regex, any other...
    - Applying Pre-processing method and Post-processing method.
    - Get assigned values.
    - Set default rule.
    - Other support methods for value-assignment.

  dev_url: https://github.com/deer-hunt/evargs
  doc_url: https://github.com/deer-hunt/evargs

extra:
  recipe-maintainers:
    - deer-hunt
